#:schema https://cdn.jsdelivr.net/gh/crate-ci/typos@master/config.schema.json

[default]
locale = "en"

[files]
extend-exclude = ["nix/patches/*.patch"]

[default.extend-words]
INVOKABLE = "INVOKABLE"
trak = "trak"
