// SPDX-FileCopyrightText: 2026 KIM Hyunjae
// SPDX-License-Identifier: AGPL-3.0-or-later

use cxx_qt_build::{CppFile, CxxQtBuilder, QmlModule};
use std::{
    collections::BTreeSet,
    env, fs,
    path::{Path, PathBuf},
    process::Command,
};

fn main() {
    let kio_include_dirs = kio_include_dirs();
    let qt_rhi_include_dirs = qt_rhi_include_dirs();
    let shader_source = bake_shaders();
    link_kio();

    let mut builder = CxxQtBuilder::new_qml_module(
        QmlModule::new("io.github.hnjae.kiriview")
            .depend("QtQuick")
            .qml_file("src/qml/Main.qml")
            .qml_file("src/qml/ImageToolBar.qml")
            .qml_file("src/qml/ImageViewport.qml")
            .qml_file("src/qml/ImageStateOverlay.qml")
            .qml_file("src/qml/ShortcutHelpDialog.qml"),
    )
    // Do not export the whole crate root as C++ headers. That makes Cargo watch
    // build artifacts such as build-dir/, including symlinks into /run.
    .crate_include_root(None)
    .cpp_file(CppFile::from("src/kiriimageview.h"))
    .file("src/apngdecoder.rs")
    .file("src/avifcompat.rs")
    .cpp_file("src/displayedimagestate.cpp")
    .cpp_file("src/imagedocumentcontroller.cpp")
    .cpp_file("src/imagedocumentnavigationcontroller.cpp")
    .cpp_file("src/imagedocumentstate.cpp")
    .cpp_file("src/imagedecodejob.cpp")
    .cpp_file("src/imagebytecost.cpp")
    .cpp_file("src/imagecandidaterepository.cpp")
    .cpp_file("src/imagecontainer.cpp")
    .cpp_file("src/imageformatregistry.cpp")
    .cpp_file("src/imageiojob.cpp")
    .cpp_file("src/imageiojobs.cpp")
    .cpp_file("src/imageloader.cpp")
    .cpp_file("src/imagenavigationmodel.cpp")
    .cpp_file("src/imageopencontroller.cpp")
    .cpp_file("src/imagepredecodecoordinator.cpp")
    .cpp_file("src/imagepresentationcontroller.cpp")
    .cpp_file("src/imageurl.cpp")
    .cpp_file("src/imagezoomstate.cpp")
    .cpp_file("src/imageanimationplayer.cpp")
    .cpp_file("src/apngdecoder.cpp")
    .cpp_file("src/kiriimagedecoder.cpp")
    .cpp_file("src/imagenavigationservice.cpp")
    .cpp_file("src/kiriimagerendernode.cpp")
    .cpp_file("src/predecodecache.cpp")
    .cpp_file("src/kiriimageview.cpp")
    .qt_module("Quick")
    .qt_module("Svg")
    .qt_module("Network")
    .qt_module("DBus");

    unsafe {
        builder = builder.cc_builder(move |cc| {
            cc.flag_if_supported("-Wno-attributes");
            cc.file(&shader_source);
            cc.include("src");
            for dir in &kio_include_dirs {
                cc.include(dir);
            }
            for dir in &qt_rhi_include_dirs {
                cc.include(dir);
            }
        });
    }

    builder.build();
}

fn bake_shaders() -> PathBuf {
    println!("cargo::rerun-if-changed=src/shaders/kiriimageview.vert");
    println!("cargo::rerun-if-changed=src/shaders/kiriimageview.frag");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR must be set"));
    let vertex_shader = out_dir.join("kiriimageview.vert.qsb");
    let fragment_shader = out_dir.join("kiriimageview.frag.qsb");

    run_qsb("src/shaders/kiriimageview.vert", &vertex_shader);
    run_qsb("src/shaders/kiriimageview.frag", &fragment_shader);

    let vertex_data = fs::read(&vertex_shader).expect("failed to read baked vertex shader");
    let fragment_data = fs::read(&fragment_shader).expect("failed to read baked fragment shader");
    let source = out_dir.join("kiriimageview_shaders.cpp");
    let mut generated = String::new();
    generated.push_str("// Generated by build.rs.\n\n");
    generated.push_str("#include \"shaders/kiriimageview_shaders.h\"\n\n");
    generated.push_str("namespace KiriView {\n");
    append_byte_array(
        &mut generated,
        "kiriImageViewVertexShader",
        "kiriImageViewVertexShaderSize",
        &vertex_data,
    );
    append_byte_array(
        &mut generated,
        "kiriImageViewFragmentShader",
        "kiriImageViewFragmentShaderSize",
        &fragment_data,
    );
    generated.push_str("}\n");
    fs::write(&source, generated).expect("failed to write generated shader source");
    source
}

fn run_qsb(input: &str, output: &Path) {
    let status = Command::new("qsb")
        .args(["--qt6", "-o"])
        .arg(output)
        .arg(input)
        .status()
        .expect("failed to run qsb; make sure Qt Shader Tools are installed");

    if !status.success() {
        panic!("qsb failed for {input}");
    }
}

fn append_byte_array(source: &mut String, name: &str, size_name: &str, data: &[u8]) {
    source.push_str("alignas(16) const unsigned char ");
    source.push_str(name);
    source.push_str("[] = {");
    for (index, byte) in data.iter().enumerate() {
        if index % 12 == 0 {
            source.push_str("\n    ");
        } else {
            source.push(' ');
        }
        source.push_str(&format!("0x{byte:02x},"));
    }
    source.push_str("\n};\nconst std::size_t ");
    source.push_str(size_name);
    source.push_str(" = sizeof(");
    source.push_str(name);
    source.push_str(");\n\n");
}

fn link_kio() {
    println!("cargo::rerun-if-env-changed=NIX_LDFLAGS");

    for dir in kio_library_dirs() {
        println!("cargo::rustc-link-search=native={}", dir.display());
    }

    println!("cargo::rustc-link-lib=KF6KIOCore");
    println!("cargo::rustc-link-lib=KF6CoreAddons");
}

fn kio_include_dirs() -> Vec<PathBuf> {
    println!("cargo::rerun-if-env-changed=NIX_CFLAGS_COMPILE");

    let mut dirs = BTreeSet::new();
    add_kf6_include_dirs(&mut dirs, Path::new("/usr/include"));
    add_qt_mkspec_include_dirs(&mut dirs, Path::new("/usr/include"));

    for path in flag_paths("NIX_CFLAGS_COMPILE", "-isystem") {
        add_kf6_include_dirs(&mut dirs, &path);
        add_qt_mkspec_include_dirs(&mut dirs, &path);
    }
    for path in flag_paths("NIX_CFLAGS_COMPILE", "-I") {
        add_kf6_include_dirs(&mut dirs, &path);
        add_qt_mkspec_include_dirs(&mut dirs, &path);
    }

    dirs.into_iter().collect()
}

fn qt_rhi_include_dirs() -> Vec<PathBuf> {
    println!("cargo::rerun-if-env-changed=NIX_CFLAGS_COMPILE");

    let mut dirs = BTreeSet::new();
    add_qt_rhi_include_dirs(&mut dirs, Path::new("/usr/include"));

    for path in flag_paths("NIX_CFLAGS_COMPILE", "-isystem") {
        add_qt_rhi_include_dirs(&mut dirs, &path);
    }
    for path in flag_paths("NIX_CFLAGS_COMPILE", "-I") {
        add_qt_rhi_include_dirs(&mut dirs, &path);
    }
    for path in pkg_config_include_dirs("Qt6Gui") {
        add_qt_rhi_include_dirs(&mut dirs, &path);
    }

    dirs.into_iter().collect()
}

fn add_qt_rhi_include_dirs(dirs: &mut BTreeSet<PathBuf>, include_root: &Path) {
    for candidate in [
        include_root.to_path_buf(),
        include_root.join("QtGui"),
        include_root.join("QtGui").join(qt_version()).join("QtGui"),
        include_root.join(qt_version()).join("QtGui"),
    ] {
        if candidate.join("rhi/qrhi.h").exists() && candidate.join("rhi/qshader.h").exists() {
            dirs.insert(candidate);
        }
    }

    for dir in versioned_qt_gui_dirs(include_root) {
        if dir.join("rhi/qrhi.h").exists() && dir.join("rhi/qshader.h").exists() {
            dirs.insert(dir);
        }
    }
}

fn versioned_qt_gui_dirs(include_root: &Path) -> Vec<PathBuf> {
    let mut dirs = Vec::new();
    for qt_gui_root in [include_root.to_path_buf(), include_root.join("QtGui")] {
        let Ok(entries) = fs::read_dir(qt_gui_root) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path().join("QtGui");
            if path.exists() {
                dirs.push(path);
            }
        }
    }
    dirs
}

fn qt_version() -> String {
    Command::new("pkg-config")
        .args(["--modversion", "Qt6Gui"])
        .output()
        .ok()
        .filter(|output| output.status.success())
        .map(|output| String::from_utf8_lossy(&output.stdout).trim().to_owned())
        .filter(|version| !version.is_empty())
        .unwrap_or_else(|| "6".to_owned())
}

fn pkg_config_include_dirs(package: &str) -> Vec<PathBuf> {
    let output = Command::new("pkg-config")
        .args(["--cflags", package])
        .output();
    let Ok(output) = output else {
        return Vec::new();
    };
    if !output.status.success() {
        return Vec::new();
    }

    let cflags = String::from_utf8_lossy(&output.stdout);
    let mut dirs = Vec::new();
    let mut tokens = cflags.split_whitespace();
    while let Some(token) = tokens.next() {
        if token == "-I" || token == "-isystem" {
            if let Some(path) = tokens.next() {
                dirs.push(PathBuf::from(path));
            }
        } else if let Some(path) = token.strip_prefix("-I")
            && !path.is_empty()
        {
            dirs.push(PathBuf::from(path));
        } else if let Some(path) = token.strip_prefix("-isystem")
            && !path.is_empty()
        {
            dirs.push(PathBuf::from(path));
        }
    }
    dirs
}

fn add_kf6_include_dirs(dirs: &mut BTreeSet<PathBuf>, include_root: &Path) {
    for suffix in ["KF6/KIOCore", "KF6/KIO", "KF6/KCoreAddons"] {
        let dir = include_root.join(suffix);
        if dir.exists() {
            dirs.insert(dir);
        }
    }
}

fn add_qt_mkspec_include_dirs(dirs: &mut BTreeSet<PathBuf>, include_root: &Path) {
    let Some(qt_root) = include_root.parent() else {
        return;
    };

    let dir = qt_root.join("mkspecs/linux-g++");
    if dir.exists() {
        dirs.insert(dir);
    }
}

fn kio_library_dirs() -> Vec<PathBuf> {
    let mut dirs = BTreeSet::new();
    for dir in ["/usr/lib/x86_64-linux-gnu", "/usr/lib"] {
        let path = PathBuf::from(dir);
        if path.exists() {
            dirs.insert(path);
        }
    }

    for path in flag_paths("NIX_LDFLAGS", "-L") {
        if contains_kio_library(&path) || contains_core_addons_library(&path) {
            dirs.insert(path);
        }
    }

    dirs.into_iter().collect()
}

fn contains_kio_library(dir: &Path) -> bool {
    dir.join("libKF6KIOCore.so").exists()
}

fn contains_core_addons_library(dir: &Path) -> bool {
    dir.join("libKF6CoreAddons.so").exists()
}

fn flag_paths(env_var: &str, flag: &str) -> Vec<PathBuf> {
    let value = env::var(env_var).unwrap_or_default();
    let mut paths = Vec::new();
    let mut tokens = value.split_whitespace();

    while let Some(token) = tokens.next() {
        if token == flag {
            if let Some(path) = tokens.next() {
                paths.push(PathBuf::from(path));
            }
        } else if let Some(path) = token.strip_prefix(flag)
            && !path.is_empty()
        {
            paths.push(PathBuf::from(path));
        }
    }

    paths
}
