// SPDX-FileCopyrightText: 2026 KIM Hyunjae
// SPDX-License-Identifier: AGPL-3.0-or-later

use cxx_qt_build::{CppFile, CxxQtBuilder, QmlModule};
use std::{
    collections::BTreeSet,
    env, fs,
    path::{Path, PathBuf},
    process::Command,
};

const CPP_CORE_SOURCES_FILE: &str = "src/cpp_core_sources.txt";
const DEFAULT_INCLUDE_ROOTS: &[&str] = &["/usr/include"];
const DEFAULT_LIBRARY_DIRS: &[&str] = &["/usr/lib/x86_64-linux-gnu", "/usr/lib"];
const NATIVE_LIBRARY_FILES: &[&str] = &[
    "libKF6Archive.so",
    "libKF6KIOCore.so",
    "libKF6CoreAddons.so",
    "libarchive.so",
    "libheif.so",
];
const NATIVE_LIBRARY_PKG_CONFIG_PACKAGES: &[&str] = &["libarchive", "libheif"];

type IncludeDirCollector = fn(&mut BTreeSet<PathBuf>, &Path);

fn main() {
    let kio_include_dirs = kio_include_dirs();
    let libarchive_include_dirs = libarchive_include_dirs();
    let libheif_include_dirs = libheif_include_dirs();
    let qt_rhi_include_dirs = qt_rhi_include_dirs();
    let shader_source = bake_shaders();
    let cpp_core_sources = cpp_core_sources();
    link_native_libraries();

    let mut builder = CxxQtBuilder::new_qml_module(
        QmlModule::new("io.github.hnjae.kiriview")
            .depend("QtQuick")
            .qml_file("src/qml/Main.qml")
            .qml_file("src/qml/ImageActions.qml")
            .qml_file("src/qml/ImageDocumentToolBar.qml")
            .qml_file("src/qml/ImageToolBar.qml")
            .qml_file("src/qml/ImagePageNavigation.qml")
            .qml_file("src/qml/ImageZoomControls.qml")
            .qml_file("src/qml/ImageViewport.qml")
            .qml_file("src/qml/ImageStateOverlay.qml")
            .qml_file("src/qml/ImageShortcut.qml")
            .qml_file("src/qml/ImageShortcuts.qml")
            .qml_file("src/qml/ShortcutHelpDialog.qml"),
    )
    // Do not export the whole crate root as C++ headers. That makes Cargo watch
    // build artifacts such as build-dir/, including symlinks into /run.
    .crate_include_root(None)
    .cpp_file(CppFile::from("src/kiriimagedocument.h"))
    .cpp_file(CppFile::from("src/kiriimageview.h"))
    .file("src/apngdecoder.rs")
    .file("src/avifcompat.rs")
    .file("src/imageformatregistry.rs")
    .file("src/imagenavigationmodel.rs")
    .file("src/imageviewportgeometry.rs")
    .file("src/imagezoomstate.rs")
    .cpp_file("src/imagedocumentcontrollerdefaults.cpp")
    .cpp_file("src/imagedecodejobdefaults.cpp")
    .cpp_file("src/imageloaderdefaults.cpp")
    .cpp_file("src/imagepredecodecoordinatordefaults.cpp")
    .cpp_file("src/apngdecoder.cpp")
    .cpp_file("src/kiriimagedocument.cpp")
    .cpp_file("src/kiriimagedecoder.cpp")
    .cpp_file("src/kiriimagerendernode.cpp")
    .cpp_file("src/kiriimageview.cpp")
    .qt_module("Quick")
    .qt_module("Svg")
    .qt_module("Network")
    .qt_module("DBus");

    for source in cpp_core_sources {
        builder = builder.cpp_file(CppFile::from(source.as_str()));
    }

    unsafe {
        builder = builder.cc_builder(move |cc| {
            cc.flag_if_supported("-Wno-attributes");
            cc.file(&shader_source);
            cc.include("src");
            for dir in &kio_include_dirs {
                cc.include(dir);
            }
            for dir in &libarchive_include_dirs {
                cc.include(dir);
            }
            for dir in &libheif_include_dirs {
                cc.include(dir);
            }
            for dir in &qt_rhi_include_dirs {
                cc.include(dir);
            }
        });
    }

    builder.build();
}

fn cpp_core_sources() -> Vec<String> {
    println!("cargo::rerun-if-changed={CPP_CORE_SOURCES_FILE}");
    fs::read_to_string(CPP_CORE_SOURCES_FILE)
        .expect("failed to read C++ core source list")
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(str::to_owned)
        .collect()
}

fn bake_shaders() -> PathBuf {
    println!("cargo::rerun-if-changed=src/shaders/kiriimageview.vert");
    println!("cargo::rerun-if-changed=src/shaders/kiriimageview.frag");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR must be set"));
    let vertex_shader = out_dir.join("kiriimageview.vert.qsb");
    let fragment_shader = out_dir.join("kiriimageview.frag.qsb");

    run_qsb("src/shaders/kiriimageview.vert", &vertex_shader);
    run_qsb("src/shaders/kiriimageview.frag", &fragment_shader);

    let vertex_data = fs::read(&vertex_shader).expect("failed to read baked vertex shader");
    let fragment_data = fs::read(&fragment_shader).expect("failed to read baked fragment shader");
    let source = out_dir.join("kiriimageview_shaders.cpp");
    let mut generated = String::new();
    generated.push_str("// Generated by build.rs.\n\n");
    generated.push_str("#include \"shaders/kiriimageview_shaders.h\"\n\n");
    generated.push_str("namespace KiriView {\n");
    append_byte_array(
        &mut generated,
        "kiriImageViewVertexShader",
        "kiriImageViewVertexShaderSize",
        &vertex_data,
    );
    append_byte_array(
        &mut generated,
        "kiriImageViewFragmentShader",
        "kiriImageViewFragmentShaderSize",
        &fragment_data,
    );
    generated.push_str("}\n");
    fs::write(&source, generated).expect("failed to write generated shader source");
    source
}

fn run_qsb(input: &str, output: &Path) {
    let status = Command::new("qsb")
        .args(["--qt6", "-o"])
        .arg(output)
        .arg(input)
        .status()
        .expect("failed to run qsb; make sure Qt Shader Tools are installed");

    if !status.success() {
        panic!("qsb failed for {input}");
    }
}

fn append_byte_array(source: &mut String, name: &str, size_name: &str, data: &[u8]) {
    source.push_str("alignas(16) const unsigned char ");
    source.push_str(name);
    source.push_str("[] = {");
    for (index, byte) in data.iter().enumerate() {
        if index % 12 == 0 {
            source.push_str("\n    ");
        } else {
            source.push(' ');
        }
        source.push_str(&format!("0x{byte:02x},"));
    }
    source.push_str("\n};\nconst std::size_t ");
    source.push_str(size_name);
    source.push_str(" = sizeof(");
    source.push_str(name);
    source.push_str(");\n\n");
}

fn link_native_libraries() {
    println!("cargo::rerun-if-env-changed=NIX_LDFLAGS");
    println!("cargo::rerun-if-env-changed=PKG_CONFIG_PATH");

    for dir in native_library_dirs() {
        println!("cargo::rustc-link-search=native={}", dir.display());
    }

    println!("cargo::rustc-link-lib=KF6Archive");
    println!("cargo::rustc-link-lib=KF6KIOCore");
    println!("cargo::rustc-link-lib=KF6CoreAddons");
    println!("cargo::rustc-link-lib=archive");
    println!("cargo::rustc-link-lib=heif");
}

fn kio_include_dirs() -> Vec<PathBuf> {
    include_dirs(&[add_kf6_include_dirs, add_qt_mkspec_include_dirs], &[])
}

fn qt_rhi_include_dirs() -> Vec<PathBuf> {
    include_dirs(&[add_qt_rhi_include_dirs], &["Qt6Gui"])
}

fn libarchive_include_dirs() -> Vec<PathBuf> {
    include_dirs(&[add_libarchive_include_dir], &["libarchive"])
}

fn libheif_include_dirs() -> Vec<PathBuf> {
    include_dirs(&[add_libheif_include_dir], &["libheif"])
}

fn include_dirs(collectors: &[IncludeDirCollector], pkg_config_packages: &[&str]) -> Vec<PathBuf> {
    println!("cargo::rerun-if-env-changed=NIX_CFLAGS_COMPILE");
    if !pkg_config_packages.is_empty() {
        println!("cargo::rerun-if-env-changed=PKG_CONFIG_PATH");
    }

    let mut dirs = BTreeSet::new();
    for root in include_candidate_roots(pkg_config_packages) {
        for collector in collectors {
            collector(&mut dirs, &root);
        }
    }

    dirs.into_iter().collect()
}

fn include_candidate_roots(pkg_config_packages: &[&str]) -> Vec<PathBuf> {
    let mut roots: Vec<PathBuf> = DEFAULT_INCLUDE_ROOTS.iter().map(PathBuf::from).collect();
    roots.extend(flag_paths("NIX_CFLAGS_COMPILE", "-isystem"));
    roots.extend(flag_paths("NIX_CFLAGS_COMPILE", "-I"));
    for package in pkg_config_packages {
        roots.extend(pkg_config_include_dirs(package));
    }
    roots
}

fn add_libarchive_include_dir(dirs: &mut BTreeSet<PathBuf>, include_root: &Path) {
    if include_root.join("archive.h").exists() && include_root.join("archive_entry.h").exists() {
        dirs.insert(include_root.to_path_buf());
    }
}

fn add_libheif_include_dir(dirs: &mut BTreeSet<PathBuf>, include_root: &Path) {
    if include_root.join("libheif").join("heif.h").exists() {
        dirs.insert(include_root.to_path_buf());
    }
}

fn add_qt_rhi_include_dirs(dirs: &mut BTreeSet<PathBuf>, include_root: &Path) {
    for candidate in [
        include_root.to_path_buf(),
        include_root.join("QtGui"),
        include_root.join("QtGui").join(qt_version()).join("QtGui"),
        include_root.join(qt_version()).join("QtGui"),
    ] {
        if candidate.join("rhi/qrhi.h").exists() && candidate.join("rhi/qshader.h").exists() {
            dirs.insert(candidate);
        }
    }

    for dir in versioned_qt_gui_dirs(include_root) {
        if dir.join("rhi/qrhi.h").exists() && dir.join("rhi/qshader.h").exists() {
            dirs.insert(dir);
        }
    }
}

fn versioned_qt_gui_dirs(include_root: &Path) -> Vec<PathBuf> {
    let mut dirs = Vec::new();
    for qt_gui_root in [include_root.to_path_buf(), include_root.join("QtGui")] {
        let Ok(entries) = fs::read_dir(qt_gui_root) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path().join("QtGui");
            if path.exists() {
                dirs.push(path);
            }
        }
    }
    dirs
}

fn qt_version() -> String {
    Command::new("pkg-config")
        .args(["--modversion", "Qt6Gui"])
        .output()
        .ok()
        .filter(|output| output.status.success())
        .map(|output| String::from_utf8_lossy(&output.stdout).trim().to_owned())
        .filter(|version| !version.is_empty())
        .unwrap_or_else(|| "6".to_owned())
}

fn pkg_config_include_dirs(package: &str) -> Vec<PathBuf> {
    pkg_config_paths(package, "--cflags", &["-I", "-isystem"])
}

fn pkg_config_paths(package: &str, pkg_config_arg: &str, flags: &[&str]) -> Vec<PathBuf> {
    let output = Command::new("pkg-config")
        .args([pkg_config_arg, package])
        .output();
    let Ok(output) = output else {
        return Vec::new();
    };
    if !output.status.success() {
        return Vec::new();
    }

    let paths = String::from_utf8_lossy(&output.stdout);
    flag_paths_from_tokens(paths.split_whitespace(), flags)
}

fn add_kf6_include_dirs(dirs: &mut BTreeSet<PathBuf>, include_root: &Path) {
    for suffix in ["KF6/KArchive", "KF6/KIOCore", "KF6/KIO", "KF6/KCoreAddons"] {
        let dir = include_root.join(suffix);
        if dir.exists() {
            dirs.insert(dir);
        }
    }
}

fn add_qt_mkspec_include_dirs(dirs: &mut BTreeSet<PathBuf>, include_root: &Path) {
    let Some(qt_root) = include_root.parent() else {
        return;
    };

    let dir = qt_root.join("mkspecs/linux-g++");
    if dir.exists() {
        dirs.insert(dir);
    }
}

fn native_library_dirs() -> Vec<PathBuf> {
    let mut dirs = BTreeSet::new();
    for dir in DEFAULT_LIBRARY_DIRS {
        let path = PathBuf::from(dir);
        if path.exists() {
            dirs.insert(path);
        }
    }

    for path in flag_paths("NIX_LDFLAGS", "-L") {
        if contains_native_library(&path) {
            dirs.insert(path);
        }
    }
    for package in NATIVE_LIBRARY_PKG_CONFIG_PACKAGES {
        for path in pkg_config_library_dirs(package) {
            dirs.insert(path);
        }
    }

    dirs.into_iter().collect()
}

fn contains_native_library(dir: &Path) -> bool {
    NATIVE_LIBRARY_FILES
        .iter()
        .any(|library| dir.join(library).exists())
}

fn pkg_config_library_dirs(package: &str) -> Vec<PathBuf> {
    pkg_config_paths(package, "--libs", &["-L"])
}

fn flag_paths(env_var: &str, flag: &str) -> Vec<PathBuf> {
    let value = env::var(env_var).unwrap_or_default();
    flag_paths_from_tokens(value.split_whitespace(), &[flag])
}

fn flag_paths_from_tokens<'a>(
    tokens: impl IntoIterator<Item = &'a str>,
    flags: &[&str],
) -> Vec<PathBuf> {
    let mut paths = Vec::new();
    let mut tokens = tokens.into_iter();

    while let Some(token) = tokens.next() {
        if flags.contains(&token) {
            if let Some(path) = tokens.next() {
                paths.push(PathBuf::from(path));
            }
        } else if let Some(path) = joined_flag_path(token, flags) {
            paths.push(PathBuf::from(path));
        }
    }

    paths
}

fn joined_flag_path<'a>(token: &'a str, flags: &[&str]) -> Option<&'a str> {
    for flag in flags {
        if let Some(path) = token.strip_prefix(flag)
            && !path.is_empty()
        {
            return Some(path);
        }
    }

    None
}
