version = 1
SPDX-PackageName = "KiriView"

[[annotations]]
path = [
  "**/*.md",
  ".biome.json",
  ".clang-format",
  ".editorconfig",
  ".envrc",
  ".gitignore",
  ".rumdl.toml",
  ".typos.toml",
  ".yamlfmt.yaml",
  "Cargo.lock",
  "Cargo.toml",
  "cargo-sources.json",
  "cog.toml",
  "devenv.lock",
  "devenv.yaml",
  "io.github.hnjae.KiriView.desktop",
  "io.github.hnjae.KiriView.json",
  "justfile",
  "opencode.jsonc",
  "po/**/*.po",
  "statix.toml",
  "tests/fixtures/**/*",
]
precedence = "closest"
SPDX-FileCopyrightText = "2026 KIM Hyunjae"
SPDX-License-Identifier = "AGPL-3.0-or-later"
