version = 1
SPDX-PackageName = "KiriView"

[[annotations]]
path = [
  # Source:
  "**/org.hnjae.kiriview.svg",
  "Cargo.lock",
  "Cargo.toml",
  "cargo-sources.json",
  "org.hnjae.kiriview.desktop",
  "org.hnjae.kiriview.json",
  "po/**/*.po",
  "tests/fixtures/**/*",

  # Dev environments:
  "justfile",
  "devenv.lock",
  "devenv.yaml",

  # Documentations:
  "**/*.md",

  # Tool configurations:
  ".gitignore",
  ".clang-format",
  ".clang-tidy",
  ".editorconfig",
  "biome.json",
  "cog.toml",
  "opencode.jsonc",
  "rumdl.toml",
  "statix.toml",
  "typos.toml",
  "yamlfmt.yaml",
]
precedence = "closest"
SPDX-FileCopyrightText = "2026 KIM Hyunjae"
SPDX-License-Identifier = "AGPL-3.0-or-later"
