#:schema https://cdn.jsdelivr.net/gh/crate-ci/typos@master/config.schema.json

[default]
locale = "en"
extend-ignore-re = ["Commit: [0-9a-f]{7,40}", "`[0-9a-f]{7,40}`"]

[default.extend-words]
INVOKABLE = "INVOKABLE"
optin = "optin"
trak = "trak"
