#!/usr/bin/env -S just --justfile

set lazy
set fallback
set unstable

set shell := ["sh", "-eu", "-c"]
set working-directory := '../..'

build_dir := "build-ninja"

_:
    @just --list

configure:
    devenv shell -- sh -eu -c 'cd libs/image-viewport && cmake -S . -B {{ build_dir }} -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON'

build: configure
    devenv shell -- sh -eu -c 'cd libs/image-viewport && cmake --build {{ build_dir }}'

[group('ci')]
test:
    devenv shell -- devenv tasks run --mode=single ci:image-viewport:test

[group('ci')]
lint:
    devenv shell -- devenv tasks run --mode=single ci:image-viewport:lint

clean:
    devenv shell -- sh -eu -c 'cd libs/image-viewport && cmake -E rm -rf {{ build_dir }}'
