[package]
name = "kiriview"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"
publish = false

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
cxx = "1.0.192"
nom-exif = { version = "3.6.0", default-features = false }
png = "0.18.1"
resvg = "0.47.0"
xdg-thumbnail = "0.1.0"

[dev-dependencies]
tempfile = "3.27.0"

[build-dependencies]
cxx-gen = "0.7.194"
proc-macro2 = "1.0.106"
