#!/usr/bin/env -S just --justfile

set unstable
set lazy
set fallback
set working-directory := '..'

_:
    @just --list

[group('ci')]
lint:
    devenv shell -- devenv tasks run --mode=single ci:app:lint

alias test-host := test

[group('ci')]
test:
    devenv shell -- devenv tasks run --mode=single ci:app:test

[group('ci')]
i18n-check:
    devenv shell -- devenv tasks run --mode=single ci:app:i18n:check

[group('ci')]
i18n-pot-check:
    devenv shell -- devenv tasks run --mode=single ci:app:i18n:pot-check

alias check := ci

[group('ci')]
ci:
    devenv shell -- devenv tasks run --mode=single ci:app

[group('build')]
i18n-update:
    devenv shell -- kiriview-update-translations
